name: Deploy to UpYun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: UpYun Deployer
        uses: her-cat/upyun-deployer@v1.0.4

      - name: Build static files
        run: hugo --minify --environment production

      - name: Deploy
        uses: her-cat/upyun-deployer@v1.0.3
        with:
          bucket: ${{ secrets.UPYUN_BUCKET }}
          operator: ${{ secrets.UPYUN_OPERATOR_NAME }}
          password: ${{ secrets.UPYUN_OPERATOR_PWD }}
          dir: 'public'
          publish_dir: 'myblog'
