name: Deploy to UpYun

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master


      - name: deploy-upyun
        uses: bwcxyk/upyun-upx-action@1.3
        env:
          UPX_SERVICENAME: ${{ secrets.UPYUN_BUCKET }}
          UPX_OPERATOR: ${{ secrets.UPYUN_OPERATOR_NAME }}
          UPX_PASSWORD: ${{ secrets.UPYUN_OPERATOR_PWD }}
          LOCAL_DIR: /
          REMOTE_DIR: /

